### ISSUE TITLE
get_mempool_geth() return error PayloadTooBig

### ISSUE THREAD

**Issue by jacko06v** [gabedonnan/pythereum#7]
while i was just playing around with pythereum i tried to see transaction on the mempool
since i'm sure the node i'm using is a geth node i've used the `get_mempool_geth()` function

that's a snippet of my code:
```

async def main() -> None:
     utils = config.load_env()
     config.load_logging()

    sender: LocalAccount = Account.from_key(utils["sender_private_key"])
    logging.info("Sender address: " + sender.address)

    # account to sign bundles & establish flashbots reputation
    signer: LocalAccount = Account.from_key(utils["flashbot_searcher_pk"])

    logging.info("Flashbot signer address: " + signer.address)

    # connect to pythereum
    rpc = EthRPC(utils["rpc"])
    block_num = await rpc.get_block_number()
    logging.info("Current block: " + str(block_num))

    await rpc.get_mempool_geth()
```
    
and `rpc.get_mempool_geth()` throws the error:
    
   ```
 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/framing.py", line 93, in read
    raise PayloadTooBig(f"over size limit ({length} > {max_size} bytes)")
websockets.exceptions.PayloadTooBig: over size limit (206501494 > 1048576 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jacopomosconi/Desktop/progetti/py_bot/main.py", line 40, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jacopomosconi/Desktop/progetti/py_bot/main.py", line 36, in main
    
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pythereum/rpc.py", line 1398, in get_mempool_geth
    msg = await self._send_message("txpool_content", [], websocket)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pythereum/rpc.py", line 401, in _send_message
    msg = await ws.recv()
          ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 948, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1009 (message too big); no close frame received
```

it seems that the payload received from the node is too big 

there is any way to work around it?

**Comment by gabedonnan** [comment]
As far as I know it is possible to increase the maximum payload size that a websocket can send or receive simply by increasing the "max_size" parameter in websocket connections, I will add this as a parameter to the constructor of the EthRPC class and it should hopefully fix the issue.

**Comment by gabedonnan** [comment]
The parameter "connection_max_payload_size" is now available in the constructor to specify the maximum payloads that can be sent and received by the websockets in EthRPC. Try it out and let me know if it works for you.

**Comment by jacko06v** [comment]
@gabedonnan just made a pull request, now it works fine
